import type { Metadata } from "next";
import "./globals.css";
import { inter, lusitana } from "./ui/fonts";
import Header from "./ui/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lusitana.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
